alteraçao
ifpb/ls-solutions pull request #1
Opened 2020-02-21 00:06 UTC by pauloprojject

2020-02-21 10:41 UTC, luizchaves requested changes
Existe sugestão de mudanças

2020-02-21 10:41 UTC, lucachaves commented on ecma/basic-hello/hello.paulo.js
> +name = "Paulo";
@pauloprojject, ao declarar um variável use const, let ou var

2020-02-25 18:57 UTC, luizchaves requested changes
Falta incluir suas soluções na pessoal pessoal, por exemplos, o arquivo ecma/basic-bmi/basic-bmi.js deveria ficar em ecma/basic-bmi/**username-suap**/basic-bmi.js

2020-02-25 19:34 UTC, pauloprojject commented
> Falta incluir suas soluções na pessoal pessoal, por exemplos, o arquivo ecma/basic-bmi/basic-bmi.js deveria ficar em ecma/basic-bmi/**username-suap**/basic-bmi.js

no caso e faria outro pull request com a pasta?

2020-02-26 00:42 UTC, luizchaves requested changes
Altere os seguintes arquivos de -> para:
- ecma/basic-bmi/pauo.victor-20192370013/basic-bmi.js => ecma/basic-bmi/pauo.victor/basic-bmi.js 
- ecma/basic-hello/hello.paulo.js => ecma/basic-hello/pauo.victor/hello.js
- ecma/basic-hello/paulo.victor-20192370013/hello.paulo.js => ecma/basic-hello/paulo.victor/hello.paulo.js
- ecma/basic-numbers/BASIC-NUMBERS.js => ecma/basic-numbers/paulo-victor/basic-numbers.js

2020-02-26 17:23 UTC, lucachaves commented
Lembrando que não preciso criar um novo PR, basta fazer a alteração e enviar para seu fork.

2020-03-02 20:02 UTC, merged